# Generated by Django 4.1a1 on 2022-08-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_claim"),
    ]

    operations = [
        migrations.AlterField(
            model_name="claim",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
