# Generated by Django 4.1 on 2022-08-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_alter_claim_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="claim",
            name="deal",
        ),
        migrations.AlterField(
            model_name="claim",
            name="admin_comment",
            field=models.TextField(blank=True, max_length=600, verbose_name="réponse"),
        ),
        migrations.AlterField(
            model_name="claim",
            name="brand",
            field=models.CharField(max_length=200, verbose_name="marque du produit"),
        ),
        migrations.AlterField(
            model_name="claim",
            name="code",
            field=models.BigIntegerField(verbose_name="référence du produit"),
        ),
        migrations.AlterField(
            model_name="claim",
            name="date",
            field=models.DateField(auto_now_add=True, verbose_name="date"),
        ),
        migrations.AlterField(
            model_name="claim",
            name="name",
            field=models.CharField(max_length=200, verbose_name="nom du produit"),
        ),
        migrations.AlterField(
            model_name="claim",
            name="status",
            field=models.CharField(
                choices=[
                    ("Accepté", "Accepté"),
                    ("Traitement en cours", "Traitement en cours"),
                    ("Refusé", "Refusé"),
                ],
                default="Traitement en cours",
                max_length=20,
                verbose_name="status de la demande",
            ),
        ),
        migrations.AlterField(
            model_name="claim",
            name="user_comment",
            field=models.TextField(max_length=600, verbose_name="commentaire"),
        ),
    ]
